### ISSUE TITLE
BDSIR.xml not working for BEAST 2.5

### ISSUE THREAD

**Issue by walterxie** [BEAST2-Dev/phylodynamics#4]
The first problem is "&" missing in the meta data section.

**Comment by walterxie** [comment]
[Fatal Error] BDSIR.xml:7:26: The reference to entity "NEWICKtype" must end with the ';' delimiter.

But the tree was accepted by IcyTree.

**Comment by walterxie** [comment]
@tgvaughan 
I am suspicious that Newick tree parser is broken, because of the error message from PhyDyn and phylodynamics packages below.
 
When I tried to run https://github.com/mrc-ide/PhyDyn/blob/master/examples/ebola/ebolaSEIRhet.xml using the latest version of code, I got the error:
“ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.5, java.lang.ExceptionInInitializerError”
I did not dig into the detail, but it looked the parser changed its behaviour, some “old” trees couldn’t be recognised.
 
In addition, Birth-death SIR XML (https://github.com/BEAST2-Dev/phylodynamics/tree/master/examples/BDSIR.xml) in phylodynamics was failed for BEAST 2.5, which looked like a problem to parse the given Newick tree. I added “&” to the meta data, but did not solve the problem.

**Comment by tgvaughan** [comment]
I'm confident this isn't a problem with treeparser: we have extensive unit tests their, and other packages have no issue.  (BTW this were a problem with treeparser, I'd raise the issue over at the beast 2 issue tracker.)

@denisekuehnert probably has a better idea of what's going on with BDSIR.

Regarding PhyDyn, I expect it's just using an out-of-date ANTLR-generated parsing class, so the fix there would be to regenerate this parser using ANTLR 4.7.  But again, I'd raise this with the PhyDyn maintainers over at [that repository](https://github.com/mrc-ide/PhyDyn).  (Actually, quickly looking at their package, they do include ANTLR 4.5, so the real issue is that BEAST 2 packages can't depend on different versions of the same library as everything shares a single namespace.  Sadly there's no easy solution to this, and we must all make sure to use the same versions... :-/ )

**Comment by denisekuehnert** [comment]
Actually @alexpopinga added this example and it might be broken now due to changes in treeparser. I'm not sure why it needs all the MASTER metadata so we might just remove that?

**Comment by tgvaughan** [comment]
Thanks Denise.

**Comment by walterxie** [comment]
@denisekuehnert @alexpopinga 
Can either of you fix this example please? It is published in http://www.beast2.org/beast-features/. If anyone is looking for Birth-death SIR, this is the 1st example that they are going to try. If you need my help, please let me know.

**Comment by denisekuehnert** [comment]
I've fixed it but it really should NOT be the first go to example as it
operates on a fixed tree which is a fairly bad idea in BDSIR (esp. with

checkTreeConsistent=TRUE) as it will hinder mixing due to the
stochastic simulations being restricted by the tree.

Can we please change that to BDSIR_serial.xml?


2018-04-29 23:34 GMT+02:00 Walter <notifications@github.com>:

**Comment by walterxie** [comment]
@denisekuehnert 
Thank you very much to fix this.

There is no BDSIR_serial.xml in BDSKY, but there is [BDSKY_sequential.xml](https://github.com/BEAST2-Dev/bdsky/blob/master/examples/BDSKY_sequential.xml), which should be the one you required. I tested using the current code, it worked and gave the correct citation in the console [stadler2013](http://www.pnas.org/content/110/1/228.full). If you agree, I will update the webpage.

**Comment by walterxie** [comment]
Done, thanks everyone.
